version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: evil-film
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: evilfilm
      MYSQL_USER: jimmy
      MYSQL_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
